// 포인트 계산 상수
export const POINT_CONSTANTS = {
  VIDEO_POINT_PER_SECOND: 0.5,
  AUDIO_POINT_PER_ATTEMPT: 1,
  RECORDING_POINT_PER_ATTEMPT: 20,
  QUIZ_ATTEMPT_POINT: 3,
  QUIZ_CORRECT_POINT: 3,
  ATTENDANCE_POINT: 50,
  MY_VOICE_OPEN_POINT: 100,
  VOICE_LIKE_POINT: 100,
  USER_VOICE_LIKE_POINT: 20,
};
