export const sentences = [
  // 출국 및 입국 (Airport & Immigration)
  { no: 1, en: "Where is the check-in counter for Korean Air?", ko: "대한항공 체크인 카운터가 어디인가요?" },
  { no: 2, en: "Can I have a window/aisle seat, please?", ko: "창가/통로 좌석으로 주세요." },
  { no: 3, en: "How many bags can I check in?", ko: "부칠 수 있는 가방은 몇 개인가요?" },
  { no: 4, en: "Do I need to take out my laptop for security screening?", ko: "보안 검색대에서 노트북을 꺼내야 하나요?" },
  { no: 5, en: "Where is the immigration counter?", ko: "출입국 심사대가 어디인가요?" },
  { no: 6, en: "I am here for tourism/business.", ko: "관광/출장 목적으로 왔습니다." },
  { no: 7, en: "I will be staying for [number] days.", ko: "저는 [일수]일 동안 머물 예정입니다." },
  { no: 8, en: "Here is my return ticket.", ko: "여기 제 귀국 항공권입니다." },
  { no: 9, en: "Where can I pick up my luggage?", ko: "수하물 찾는 곳이 어디인가요?" },
  { no: 10, en: "My baggage is missing. What should I do?", ko: "제 짐이 없어졌어요. 어떻게 해야 하나요?" },

  // 교통 (Transportation)
  { no: 11, en: "Where can I get a taxi?", ko: "택시는 어디에서 탈 수 있나요?" },
  { no: 12, en: "How much is the fare to [destination]?", ko: "[목적지]까지 요금이 얼마인가요?" },
  { no: 13, en: "Can you take me to this address?", ko: "이 주소로 가주세요." },
  { no: 14, en: "Does this bus go to [place]?", ko: "이 버스가 [장소]에 가나요?" },
  { no: 15, en: "Where is the nearest subway station?", ko: "가장 가까운 지하철역이 어디인가요?" },
  { no: 16, en: "How do I get to [place] by public transport?", ko: "대중교통으로 [장소]에 가려면 어떻게 해야 하나요?" },
  { no: 17, en: "How much is a one-day subway pass?", ko: "하루 이용권 가격이 얼마인가요?" },
  { no: 18, en: "Is this the right train for [destination]?", ko: "이 기차가 [목적지]로 가는 것이 맞나요?" },
  { no: 19, en: "Do I need to transfer to another line?", ko: "다른 노선으로 갈아타야 하나요?" },
  { no: 20, en: "Where can I rent a car?", ko: "렌터카를 어디에서 빌릴 수 있나요?" },

  // 숙박 (Hotel)
  { no: 21, en: "I have a reservation under the name [name].", ko: "[이름]으로 예약했어요." },
  { no: 22, en: "Do you have any rooms available?", ko: "빈 방이 있나요?" },
  { no: 23, en: "Can I see the room first?", ko: "방을 먼저 볼 수 있을까요?" },
  { no: 24, en: "What time is check-in/check-out?", ko: "체크인/체크아웃 시간이 언제인가요?" },
  { no: 25, en: "Can I get a room with a view?", ko: "전망 좋은 방으로 받을 수 있나요?" },
  { no: 26, en: "Does the room include breakfast?", ko: "조식이 포함되어 있나요?" },
  { no: 27, en: "The Wi-Fi is not working in my room.", ko: "제 방에서 와이파이가 안 돼요." },
  { no: 28, en: "Can you send someone to fix it?", ko: "수리해 줄 사람을 보내주실 수 있나요?" },
  { no: 29, en: "I need an extra towel, please.", ko: "수건을 추가로 주세요." },
  { no: 30, en: "Can I leave my luggage here after check-out?", ko: "체크아웃 후에 짐을 맡길 수 있나요?" },

  // 식사 (Dining)
  { no: 31, en: "Do you have an English menu?", ko: "영어 메뉴가 있나요?" },
  { no: 32, en: "What do you recommend?", ko: "추천 메뉴는 무엇인가요?" },
  { no: 33, en: "I would like to order [dish name].", ko: "[음식 이름]을 주문하고 싶어요." },
  { no: 34, en: "Is this dish spicy?", ko: "이 음식은 매운가요?" },
  { no: 35, en: "Can I have this without [ingredient]?", ko: "이 요리에서 [재료] 빼고 해주실 수 있나요?" },
  { no: 36, en: "Help!", ko: "도와주세요!" },
  { no: 37, en: "Call the police!", ko: "경찰을 불러주세요!" },
  { no: 38, en: "I lost my passport.", ko: "여권을 잃어버렸어요." },
  { no: 39, en: "I need to see a doctor.", ko: "병원에 가야 해요." },
  { no: 40, en: "Where is the nearest hospital?", ko: "가장 가까운 병원이 어디인가요?" },

  // 쇼핑 (Shopping)
  { no: 41, en: "How much is this?", ko: "이거 얼마예요?" },
  { no: 42, en: "Do you have this in a different color/size?", ko: "이거 다른 색상/사이즈 있나요?" },
  { no: 43, en: "Can I try this on?", ko: "입어봐도 될까요?" },
  { no: 44, en: "Do you accept credit cards?", ko: "신용카드 사용 가능해요?" },
  { no: 45, en: "Can I get a discount?", ko: "할인 가능할까요?" },
  { no: 46, en: "I’ll take this.", ko: "이거 살게요." },
  { no: 47, en: "Can I return this if it doesn’t fit?", ko: "맞지 않으면 환불 가능한가요?" },
  { no: 48, en: "Where is the tax refund counter?", ko: "택스 리펀드 받는 곳이 어디인가요?" },
  { no: 49, en: "Can you gift-wrap this?", ko: "선물 포장해 주실 수 있나요?" },
  { no: 50, en: "Do you have a shopping bag?", ko: "쇼핑백 있나요?" },

  // 식사 (Dining)
  { no: 51, en: "Do you have an English menu?", ko: "영어 메뉴가 있나요?" },
  { no: 52, en: "What do you recommend?", ko: "추천 메뉴는 무엇인가요?" },
  { no: 53, en: "I would like to order [dish name].", ko: "[음식 이름]을 주문하고 싶어요." },
  { no: 54, en: "Is this dish spicy?", ko: "이 음식은 매운가요?" },
  { no: 55, en: "Can I have this without [ingredient]?", ko: "이 요리에서 [재료] 빼고 해주실 수 있나요?" },
  { no: 56, en: "I have a food allergy to [ingredient].", ko: "저는 [재료] 알레르기가 있어요." },
  { no: 57, en: "Can I get the check, please?", ko: "계산서 주세요." },
  { no: 58, en: "Do you take credit cards?", ko: "신용카드 사용 가능한가요?" },
  { no: 59, en: "Is there a vegetarian option?", ko: "채식 메뉴가 있나요?" },
  { no: 60, en: "This is delicious!", ko: "정말 맛있어요!" },

  // 관광 (Sightseeing)
  { no: 61, en: "Where is the tourist information center?", ko: "관광 안내소가 어디인가요?" },
  { no: 62, en: "What are the must-visit places here?", ko: "여기에서 꼭 가봐야 할 곳은 어디인가요?" },
  { no: 63, en: "How much is the entrance fee?", ko: "입장료가 얼마인가요?" },
  { no: 64, en: "What time does this place open/close?", ko: "이곳은 몇 시에 열고 닫나요?" },
  { no: 65, en: "Is there a guided tour available?", ko: "가이드 투어가 있나요?" },
  { no: 66, en: "Can I take pictures here?", ko: "여기서 사진을 찍어도 되나요?" },
  { no: 67, en: "Where is the best place to take pictures?", ko: "사진 찍기 좋은 장소는 어디인가요?" },
  { no: 68, en: "Are there any special events happening today?", ko: "오늘 특별한 행사가 있나요?" },
  { no: 69, en: "How do I get to [tourist spot]?", ko: "[관광지]로 가려면 어떻게 해야 하나요?" },
  { no: 70, en: "Is there an audio guide available?", ko: "오디오 가이드가 있나요?" },

  // 커뮤니케이션 (Communication)
  { no: 71, en: "Do you speak English?", ko: "영어를 하실 수 있나요?" },
  { no: 72, en: "Can you speak more slowly, please?", ko: "좀 더 천천히 말씀해 주실 수 있나요?" },
  { no: 73, en: "Can you write it down for me?", ko: "그것을 적어 주실 수 있나요?" },
  { no: 74, en: "How do you say this in English?", ko: "이걸 영어로 어떻게 말하나요?" },
  { no: 75, en: "Could you repeat that, please?", ko: "다시 한 번 말씀해 주시겠어요?" },
  { no: 76, en: "I don’t understand.", ko: "이해하지 못했어요." },
  { no: 77, en: "I’m learning English.", ko: "저는 영어를 배우고 있어요." },
  { no: 78, en: "Can you recommend a good language app?", ko: "좋은 언어 학습 앱을 추천해 주실 수 있나요?" },
  { no: 79, en: "I need a translator.", ko: "통역사가 필요해요." },
  { no: 80, en: "Could you help me with this translation?", ko: "이 번역을 도와주실 수 있나요?" },

  // 은행 & 환전 (Bank & Exchange)
  { no: 81, en: "Where is the nearest ATM?", ko: "가장 가까운 ATM 이 어디인가요?" },
  { no: 82, en: "Can I exchange money here?", ko: "여기서 환전할 수 있나요?" },
  { no: 83, en: "What is the exchange rate for USD to [currency]?", ko: "미국 달러를 [통화]로 바꾸는 환율이 얼마인가요?" },
  { no: 84, en: "Can I withdraw cash with this card?", ko: "이 카드로 현금을 인출할 수 있나요?" },
  { no: 85, en: "Do you accept traveler’s checks?", ko: "여행자 수표를 받나요?" },
  { no: 86, en: "I lost my credit card. Can you help me?", ko: "신용카드를 잃어버렸어요. 도와줄 수 있나요?" },
  { no: 87, en: "I need to report a lost or stolen card.", ko: "분실 또는 도난 신고를 해야 합니다." },
  { no: 88, en: "How long does an international transfer take?", ko: "국제 송금은 얼마나 걸리나요?" },
  { no: 89, en: "Is there a fee for currency exchange?", ko: "환전 수수료가 있나요?" },
  { no: 90, en: "Can I open a bank account as a tourist?", ko: "관광객으로 은행 계좌를 개설할 수 있나요?" },

  // 긴급 상황 (Emergency)
  { no: 91, en: "Help!", ko: "도와주세요!" },
  { no: 92, en: "Call the police!", ko: "경찰을 불러주세요!" },
  { no: 93, en: "I lost my passport.", ko: "여권을 잃어버렸어요." },
  { no: 94, en: "I need to see a doctor.", ko: "병원에 가야 해요." },
  { no: 95, en: "Where is the nearest hospital?", ko: "가장 가까운 병원이 어디인가요?" },
  { no: 96, en: "I have a medical emergency.", ko: "응급 상황이에요." },
  { no: 97, en: "My wallet has been stolen.", ko: "지갑을 도난당했어요." },
  { no: 98, en: "Can you call an ambulance?", ko: "구급차 불러줄 수 있나요?" },
  { no: 99, en: "Where is the embassy of Korea?", ko: "대한민국 대사관이 어디인가요?" },
  { no: 100, en: "I need a translator.", ko: "통역사가 필요해요." },
];
