import type { Metadata } from "next";
import "./globals.css";
import { NextLayout } from "@/app/providers";
import { Noto_Sans_KR } from "next/font/google";
import AuthProvider from "@/app/auth-provider";

const inter = Noto_Sans_KR({
  weight: ["400", "600", "900"],
  style: "normal",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "100 Sentences",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${inter.className} antialiased`}>
        <AuthProvider>
          <NextLayout>{children}</NextLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
