import type { Metadata } from "next";
import "./globals.css";
import { NextLayout } from "@/app/providers";
import { Noto_Sans_KR } from "next/font/google";
import AuthProvider from "@/app/auth-provider";
import { Toaster } from "react-hot-toast";

const inter = Noto_Sans_KR({
  weight: ["400", "600", "900"],
  style: "normal",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Friending",
  description: "Generated by create next app",
  verification: {
    other: {
      "naver-site-verification": "127bb5d3e9929a7eee7513ad139dfe16ef499587",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${inter.className} antialiased`}>
        <AuthProvider>
          <NextLayout>{children}</NextLayout>
        </AuthProvider>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
